//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinecraftJsonGenerator.Languages {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pl() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinecraftJsonGenerator.Languages.pl", typeof(pl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Generuj Pliki.
        /// </summary>
        internal static string buttonGenerateAll {
            get {
                return ResourceManager.GetString("buttonGenerateAll", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Generuj Pliki Blockstates.
        /// </summary>
        internal static string buttonGenerateBlockstates {
            get {
                return ResourceManager.GetString("buttonGenerateBlockstates", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Generuj Pliki Itemów.
        /// </summary>
        internal static string buttonGenerateItems {
            get {
                return ResourceManager.GetString("buttonGenerateItems", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Generuj Pliki Modeli.
        /// </summary>
        internal static string buttonGenerateModels {
            get {
                return ResourceManager.GetString("buttonGenerateModels", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy wygenerować zestaw bloków, wariant podstawowy (jeden model) oraz wariant z wieloma modelami.
        /// </summary>
        internal static string buttonSingleModel {
            get {
                return ResourceManager.GetString("buttonSingleModel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ustawienia Efektu Końcowego.
        /// </summary>
        internal static string groupFinalResult {
            get {
                return ResourceManager.GetString("groupFinalResult", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dane wejściowe.
        /// </summary>
        internal static string groupInput {
            get {
                return ResourceManager.GetString("groupInput", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dane wyjściowe.
        /// </summary>
        internal static string groupOutput {
            get {
                return ResourceManager.GetString("groupOutput", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwy tekstur dla.
        /// </summary>
        internal static string input_customizeBlockTextures_groupTextureNames {
            get {
                return ResourceManager.GetString("input_customizeBlockTextures_groupTextureNames", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wygląd.
        /// </summary>
        internal static string input_customizeBlockTextures_groupTextureSettings {
            get {
                return ResourceManager.GetString("input_customizeBlockTextures_groupTextureSettings", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ustawienia Bloku.
        /// </summary>
        internal static string input_groupBlockSettings {
            get {
                return ResourceManager.GetString("input_groupBlockSettings", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kontrolki.
        /// </summary>
        internal static string input_groupControlls {
            get {
                return ResourceManager.GetString("input_groupControlls", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ustawienia Wyglądu Bloku.
        /// </summary>
        internal static string input_groupCustomizeBlockTextures {
            get {
                return ResourceManager.GetString("input_groupCustomizeBlockTextures", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Folder z zasobami.
        /// </summary>
        internal static string input_groupDirectoryPath {
            get {
                return ResourceManager.GetString("input_groupDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podstawowa.
        /// </summary>
        internal static string labelBaseTexture {
            get {
                return ResourceManager.GetString("labelBaseTexture", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazwa bloku.
        /// </summary>
        internal static string labelBlockName {
            get {
                return ResourceManager.GetString("labelBlockName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Typ bloku.
        /// </summary>
        internal static string labelBlockType {
            get {
                return ResourceManager.GetString("labelBlockType", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Namespace.
        /// </summary>
        internal static string labelNamespace {
            get {
                return ResourceManager.GetString("labelNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Inna nazwa bloku.
        /// </summary>
        internal static string labelSecondBlockName {
            get {
                return ResourceManager.GetString("labelSecondBlockName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wariant drugi.
        /// </summary>
        internal static string labelSecondTexture {
            get {
                return ResourceManager.GetString("labelSecondTexture", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ilość wariantów.
        /// </summary>
        internal static string labelVariantCount {
            get {
                return ResourceManager.GetString("labelVariantCount", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Schemat wariantów.
        /// </summary>
        internal static string labelVariantSuffix {
            get {
                return ResourceManager.GetString("labelVariantSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ścieżka.
        /// </summary>
        internal static string textPath {
            get {
                return ResourceManager.GetString("textPath", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podmienić.
        /// </summary>
        internal static string textReplace {
            get {
                return ResourceManager.GetString("textReplace", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Przeglądaj.
        /// </summary>
        internal static string textSearch {
            get {
                return ResourceManager.GetString("textSearch", resourceCulture);
            }
        }
    }
}
